### ISSUE TITLE
Staging server

### ISSUE THREAD

**Issue by sutty-coop** [link-rot-project/facing.life#3]
Host it somewhere for reviewing

**Comment by walkerlj0** [comment]
@fauno any updates here?

**Comment by fauno** [comment]
It's uploaded here, a co-worker will be testing the mirroring and I also added automatic tests.

https://facing-life.testing.sutty.nl/

It's currently failing because of missing alternative fonts and something Elementor does with the menu that the check doesn't support, but it's still needed for the menu to open.

https://github.com/link-rot-project/facing.life/actions/runs/5717873563/job/15492500631
