### ISSUE TITLE
Add Parallax Scrolling Effect

### ISSUE THREAD

**Issue by walkerlj0** [link-rot-project/facing.life#6]
The original Facing Life has a parallax effect (See this Vimeo Video)

This counts as additional services, can you add the CSS to make the website appear as it does here?

**Comment by brandontauszik** [comment]
Hi @sutty-coop I reached out to the web firm that built Facing Life and they said the reason the parallax scroll had stopped is because a premium plugin had become unlicensed and was not up to date. I updated and the scroll effect is back https://www.facing.life/lynn/ You may need to redownload the whole site now. Let me know if you have any q's

**Comment by sutty-coop** [comment]
Hi, thanks, I see there was a general upgrade and some things on the site changed, for now I'll ignore them and stick to the parallax effect

**Comment by sutty-coop** [comment]
Ended up upgrading all content because it got too complex.  You can review it on the staging website!

**Comment by brandontauszik** [comment]
Yea it was a bunch of old plugins that got updated. The current / only issue is somehow with the updates the cinemagraphs all went to 1x1 square, all over the site. They were 4x5 previously and need to be 4x5 again.

<img width="1571" alt="fl_new" src="https://github.com/link-rot-project/facing.life/assets/141079987/ffb8d0cc-7ce8-45ec-8e6a-bcc80c903c6b">
<img width="1218" alt="fl_original" src="https://github.com/link-rot-project/facing.life/assets/141079987/4a9bd431-3bd0-472f-8e20-c1ab353055df">
