### ISSUE TITLE
Get Information for new Domains

### ISSUE THREAD

**Issue by walkerlj0** [link-rot-project/facing.life#7]
I know you will need a new domain name, what else is needed for publishing? Do we need to set up something special?

@sutty-coop can you tell me/ show screenshots of what info I need to provide about domains in order to publish?

**Comment by sutty-coop** [comment]
Screenshot for Njalla, it should be similar with other providers.  The dot at the end of `api.distributed.press.` is important and required (it means it's a full domain and not a subdomain of the current one).

I prefer to keep TTLs lower so they can be changed quickly when needed.

![image](https://github.com/link-rot-project/facing.life/assets/113475467/af17acbb-b5c9-418f-beb8-efbd93d054e6)

![image](https://github.com/link-rot-project/facing.life/assets/113475467/fee15e7b-6d32-47dc-b5e4-01d6cca0d7f0)

**Comment by walkerlj0** [comment]
Ready to roll

**Comment by walkerlj0** [comment]
@sutty-coop need to use token to create this

**Comment by walkerlj0** [comment]
<img width="1152" alt="Screenshot 2023-09-25 at 1 47 11 PM" src="https://github.com/link-rot-project/facing.life/assets/66978602/8b5f1e0c-4a9e-4880-8645-488544d7d2e7">

**Comment by walkerlj0** [comment]
@sutty-coop can you find a solution for using an alias

**Comment by fauno** [comment]
Well, apparently GoDaddy doesn't support ANAME/ALIAS records and CNAME on the main domain is discouraged/disallowed, so the options would be:

* Change the A record to point to Distributed Press current address. If DP ever changes IP address you would have to update this record accordingly, since the site will go down.  This can be mitigated by lowering the A record TTL and set an uptime monitor for facing.life (which should be good anyway).  If DP does change IP address, you'll know right away.

* Change nameservers to another provider that supports ALIAS/ANAME. For instance, [dns.he.net](https://dns.he.net) has been working good for us for many years.  No need to change from GoDaddy as registrar, just create an account on he.net and change nameserver delegation on GD to it.  This is a bit more involved but it'll be resistant to DP changing addresses.

Let me know what you decide and I'll provide the corresponding DNS records.

**Comment by walkerlj0** [comment]
Hey
I'm not sure we will be able to change the nameserver as we just purchased
9 years for each domain 😔.

Can you help me understand what the difference is between having an A name
record pointing to a Sutty IP and using the NS record? Either way if
servers went down, wouldn't the hosting disappear? Or is there just an
added risk the the IP might get randomly reassigned?

**Comment by fauno** [comment]
> I'm not sure we will be able to change the nameserver as we just purchased 9 years for each domain 😔.

Of course! I meant GoDaddy will still be the registrar you paid for 9 years, but it doesn't need to be the nameserver.  You can delegate this role to any other provider.  Many registrars if not all conflate the two, registrar and nameserver, but they give you the option to delegate (not transfer).

> Can you help me understand what the difference is between having an A name record pointing to a Sutty IP and using the NS record? Either way if servers went down, wouldn't the hosting disappear? Or is there just an added risk the the IP might get randomly reassigned?

They both will point to a Distributed Press address, but the A record requires DP to change addresses carefully, because as you said, the sites will be down or they could be randomly reassigned to another entity.  An ALIAS record always points to the latest DP address, so any change is transparent for you and doesn't require any coordination.

The A/ALIAS records are only required for visits to https://facing.life, other protocols only require the _dnslink subdomain and gateways use this, so even if the main host goes down, as long as someone's sharing the site over IPFS/Holepunch, it'll still be accessible.

**Comment by brandontauszik** [comment]
This is over my head!

**Comment by fauno** [comment]
@walkerlj0 let me know when we can do this

**Comment by walkerlj0** [comment]
@fauno if you write the steps here (e.g. visit this site, change this field, do this thing) I can do it, or we can do it on Friday Oct 13?

**Comment by walkerlj0** [comment]
Now serving via Dist Press
